---
title: "Gaude"
author: "Christina Schmidt"
date: "January 2025"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
---
```{r, warning=FALSE, message=FALSE}
#load the needed:
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function

#Function:
Load_GeneSet <- function(File, InputFile, GenesetName, Save=FALSE){
  #Open the gmt or csv file:
  if(File=="gmt"){
    library(GSEABase)
    gmtfile <- InputFile
    genesets = GSEABase::getGmt(con = gmtfile)
    genesets = unlist(genesets)
    
    gene_to_term =plyr::ldply(genesets,function(geneset){
      temp <- geneIds(geneset)
      temp2 <- setName(geneset)
      temp3 <- as.data.frame(cbind(temp,rep(temp2,length(temp))))
    },.progress = plyr::progress_text())
    names(gene_to_term) <- c("gene","term")
    #return(gene_to_term[complete.cases(gene_to_term),])
    DF <- gene_to_term
  }
  else if(File=="csv"){
    DF <- read.csv(paste(InputFile))
  }
  else{
    paste("File is either gmt or csv and InputFile type needs to match File")
  }
  #Add the number of genes present in each pathway
  DF$Count <- 1
  DF_Mean <- aggregate(DF$Count, by=list(term=DF$term), FUN=sum)
  names(DF_Mean)[names(DF_Mean) == "x"] <- "Genes_in_Pathway"
  DF <- merge(x= DF[,-3], y=DF_Mean,by="term", all.x=TRUE)
  #Return and save the DF as .csv
  if(Save==FALSE){
    Output <- DF
  }
  else if(Save==TRUE){
    dir.create("Output_GeneSets")
    write.csv(DF, paste("Output_GeneSets/", GenesetName, ".csv"))
    Output <- DF
  }
  else{
    paste("Please select Save=TRUE or Save=FALSE")
  }
}
```

# Samples
Gene set curated based on Recon2 that has been developed as part of the work of [Gaude et al.](https://www.nature.com/articles/ncomms13041#Sec16). Supplemetary Table 3 and 4 where downloaded from the manuscript.
\

# The Data
```{r}
MetabolicSig <-Load_GeneSet(File="csv", 
                InputFile="Input/41467_2016_BFncomms13041_MOESM340_ESM.csv")

# For the MetabolicSig we will also add a column informing us if the enzyme is unique for the pathway:
Correction_MetabolicSig <- read.csv("Input/41467_2016_BFncomms13041_MOESM341_ESM.csv")%>% 
    mutate(UniqueGene = case_when(pathway =="1" ~ 'Unique',
                                  TRUE ~ 'In multiple Pathways'))
MetabolicSig <-merge(x=MetabolicSig[,-3], y=Correction_MetabolicSig[,-2], by ="gene", all.x=TRUE)

```
\
Save DF as .csv file
```{r}
write.csv(MetabolicSig, paste( "Compilled_MetabolicSig_", Sys.Date(), ".csv", sep=""), row.names=FALSE)
```

# Information about package used and versions 
```{r session_info, echo=FALSE}
options(width = 120)
sessioninfo::session_info()
```
