---
title: "core Metabolomics"
author:
  - name: Christina Schmidt
    affiliation:
    - Heidelberg University
output:
  html_document:
    self_contained: true
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: show
vignette: >
  %\VignetteIndexEntry{Standard Metabolomics}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
bibliography: bibliography.bib
editor_options:
  chunk_output_type: console
---

<style>
.vscroll-plot {
    width: 850px;
    height: 500px;
    overflow-y: scroll;
    overflow-x: hidden;
}
</style>

```{r chunk_setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

install the required dependencies and load the libraries:
```{r, message=FALSE, warning=FALSE}
#dependencies that need to be loaded:
library(MetaProViz)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibble)
library(readxl)

# Convert All Text to UTF-8
sanitize_df <- function(df) {
  df[] <- lapply(df, function(col) {
    if (is.character(col)) {
      col <- ifelse(is.na(col), NA, col)  # Ensure NAs remain NAs
      col <- iconv(col, from = "UTF-8", to = "UTF-8", sub = "")  # Remove non-UTF-8 characters
      col <- gsub("[[:cntrl:]]", "", col)  # Remove control characters (but not NA)
      col <- substr(col, 1, 30000)  # Truncate long cells
    }
    return(col)
  })
  return(df)
}

# Make lists
convert_to_df <- function(path) {
  df <- as.data.frame(
    suppressMessages(
    readr::read_csv(path)
    )
  )
}

```

# Compile additional sheet for Extended Data Table 3
To showcase how many features are left/flanked after each stage of the processing workflow.\
\
In order to do this we will compile a new sheet with those informations. 
```{r}
# Open Excel file from BioRxiv branch and read in the data
read_xlsx_all <- function(url) {
  tmp <- tempfile(fileext = ".xlsx")
  download.file(url, tmp, mode = "wb")
  
  sheets <- excel_sheets(tmp)
  lapply(sheets, function(s) read_excel(tmp, sheet = s)) |>
    setNames(sheets)
}

data_list <- read_xlsx_all(
  "https://raw.githubusercontent.com/saezlab/MetaProViz/BioRxiv/Extended%20Data%20Table%203_Cells-Exometabolomics.xlsx"
)

# Open feature filtering sheet that was not included in the original Extended Data Table 3 and extract the relevant information:
FeatureFilt <- read.csv(
  "https://raw.githubusercontent.com/saezlab/MetaProViz/BioRxiv/Cells_CoRe/MetaProViz_Results/Processing/processing/core_processing_Filtered_metabolites_2025-08-01.csv"
)

# Extract the relevant information and compile a new sheet
AffectedMetab <- c("N-acetylaspartylglutamate", "S-(2-succinyl)cysteine", "3-Dehydro-L-threonate", "aconitate" ,"arginine"  ,"fumarate", "gluconate",  "malate", "methylarginine" , "ornithine", "hypotaurine")

PoolCV <- data_list[["PoolEstimationCV"]]%>%
  dplyr::filter(CV >= 30 | Metabolite %in%  AffectedMetab)%>%
  dplyr::select("Metabolite", "CV")%>%
  dplyr::rename("PoolEstimationCV" = "CV")

MediaCV <- data_list[["MediaBlankCV"]]%>%
  dplyr::filter(CV >= 30 | Metabolite %in%  AffectedMetab)%>%
  dplyr::select("Metabolite", "CV")%>%
  dplyr::rename("MediaBlankCV" = "CV")

FeatureFilt$`80%-filtering` <- "Modifiedfiltering_0.8"
FeatureFilt <- FeatureFilt%>%
 dplyr::rename("Metabolite" = "RemovedMetabolites")%>%
  dplyr::select("Metabolite", "80%-filtering")

# Combine them into one DF:
Merged <- PoolCV %>%
  full_join(MediaCV, by = "Metabolite") %>%
  full_join(FeatureFilt, by = "Metabolite")%>%
  mutate(
    removed = !is.na(`80%-filtering`) & (!is.na(PoolEstimationCV) | !is.na(MediaBlankCV))
  )%>%
  mutate(`80%-filtering` = if_else(!is.na(`80%-filtering`), TRUE, FALSE)
         )%>%
  arrange(desc(removed))

# save as csv
write.csv2(
    sanitize_df(Merged),
    "Cells_CoRe/Merged_FilteredFeatures.csv",
    row.names = FALSE
)
```

# Session information

```{r session_info, echo=FALSE}
options(width = 120)
sessionInfo()
```
