---
title: "Hallmarks"
author: "Christina Schmidt"
date: "July 2024"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
---
```{r, warning=FALSE, message=FALSE}
#load the needed:
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function

#Function:
Load_GeneSet <- function(File, InputFile, GenesetName, Save=FALSE){
  #Open the gmt or csv file:
  if(File=="gmt"){
    library(GSEABase)
    gmtfile <- InputFile
    genesets = GSEABase::getGmt(con = gmtfile)
    genesets = unlist(genesets)
    
    gene_to_term =plyr::ldply(genesets,function(geneset){
      temp <- geneIds(geneset)
      temp2 <- setName(geneset)
      temp3 <- as.data.frame(cbind(temp,rep(temp2,length(temp))))
    },.progress = plyr::progress_text())
    names(gene_to_term) <- c("gene","term")
    #return(gene_to_term[complete.cases(gene_to_term),])
    DF <- gene_to_term
  }
  else if(File=="csv"){
    DF <- read.csv(paste(InputFile))
  }
  else{
    paste("File is either gmt or csv and InputFile type needs to match File")
  }
  #Add the number of genes present in each pathway
  DF$Count <- 1
  DF_Mean <- aggregate(DF$Count, by=list(term=DF$term), FUN=sum)
  names(DF_Mean)[names(DF_Mean) == "x"] <- "Genes_in_Pathway"
  DF <- merge(x= DF[,-3], y=DF_Mean,by="term", all.x=TRUE)
  #Return and save the DF as .csv
  if(Save==FALSE){
    Output <- DF
  }
  else if(Save==TRUE){
    dir.create("Output_GeneSets")
    write.csv(DF, paste("Output_GeneSets/", GenesetName, ".csv"))
    Output <- DF
  }
  else{
    paste("Please select Save=TRUE or Save=FALSE")
  }
}
```

# Samples
Gene sets downloaded from [MsigDB](https://www.gsea-msigdb.org/gsea/msigdb) on 09.10.2023: Hallmarks
\

# The Data
```{r}
Hallmarks <-Load_GeneSet(File="gmt", 
                InputFile="Input/h.all.v2023.1.Hs.symbols.gmt")

```
\
Save DF as .csv file
```{r}
write.csv(Hallmarks[,c(1:2)], "Hallmarks.csv")
```

# Information about package used and versions 
```{r session_info, echo=FALSE}
options(width = 120)
sessioninfo::session_info()
```
