default:
  - "#88CCEE"
  - "#DDCC77"
  - "#661100"
  - "#332288"
  - "#AA4499"
  - "#999933"
  - "#44AA99"
  - "#882215"
  - "#6699CC"
  - "#117733"
  - "#888888"
  - "#CC6677"
  - "black"
  - "gold1"
  - "darkorchid4"
  - "red"
  - "orange"
