# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples and adapted
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

name: Build_gh-pages.yml #shown when action is run

jobs:

  pkgdown:

    runs-on: ubuntu-latest
    container:
      image: rocker/r-ubuntu:latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} #to push results to gh-pages branch!

    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'schedule' && github.ref == 'refs/heads/development')

    steps: #Series of steps that is executed sequencially: https://github.com/r-lib/actions/
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libglpk40 git libxml2-dev libcurl4-openssl-dev libssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev cmake
          echo "R_VERSION=`R --version | head -n 1 | awk '{print $3}' | cut -b 1-3`" >> $GITHUB_ENV
          echo "R_LIBS_USER=`Rscript -e 'cat(.libPaths()[1L])'`" >> $GITHUB_ENV

      - uses: actions/checkout@v4 # goes to gh-pages branch to work there

      - uses: r-lib/actions/setup-pandoc@v2 #installs pandoc

      - name: Set up R dependency cache
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ env.R_VERSION }}
          restore-keys: |
            ${{ runner.os }}-r-${{ env.R_VERSION }}

      - name: Install fgsea & pkgdown
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_github("r-lib/remotes")'  # see: https://github.com/r-lib/remotes/issues/798
          Rscript -e 'remotes::install_github("ctlab/fgsea")'  # see: https://github.com/ctlab/fgsea/issues/165
          Rscript -e 'install.packages("pkgdown")'

      - name: Install MetaProViz from GitHub by remotes
        run: Rscript -e 'remotes::install_github("saezlab/MetaProViz")' #we install from GitHub as if we are a random user

      - name: Build pkgdown site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
